name: "Advanced Workflow with Expressions"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Branch Name
        run: 'echo "Running on branch: ${{ github.ref }}"'


      - name: Run only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This job runs only on the main branch."

  conditional-job:
    runs-on: ubuntu-latest
    needs: check-branch
    steps:
      - name: Check Event Type
        run: echo "This was triggered by: ${{ github.event_name }}"

      - name: Run only for push event
        if: github.event_name == 'push'
        run: echo "This step runs only for push events."

      - name: Run only if commit message contains 'deploy'
        if: contains(github.event.head_commit.message, 'deploy')
        run: echo "Deployment keyword detected in commit message."

  use-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Use format() Function
        run: echo "${{ format('Triggered by {0} on branch {1}', github.event_name, github.ref_name) }}"

      - name: Check If Branch Starts With "feature/"
        if: startsWith(github.ref_name, 'feature/')
        run: echo "This step runs only for feature branches."

      - name: Convert JSON to String
        run: echo "Repository Info: ${{ toJSON(github.repository) }}"

  environment-variables:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Print Environment Variables
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Repository Name: $REPO_NAME"
