name: Conditional Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Execution with Else
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "Running on the main branch"
          else
            echo "Running on another branch"
          fi