
name: Clouhub Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout code repo
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8/Cache dependencies
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn -B clean package -s .maven/settings.xml
      
    - name: Upload Artifact
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
         name: Package
         path: staging
      
    - name: Deploy with maven
      run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
      env:
        ANYPOINT_PALTFORM_USERNAME: ${{secrets.ANYPOINT_PALTFORM_USERNAME}}
        ANYPOINT_PALTFORM_PASSWORD: ${{secrets.ANYPOINT_PALTFORM_PASSWORD}}
      
